left_arm:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 5.0050000000000000001
  kinematics_solver_timeout: 5.0050000000000000001
  position_only_ik: True

right_arm:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 5.0050000000000000001
  kinematics_solver_timeout: 5.0050000000000000001
  position_only_ik: True

both_arms:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 5.0050000000000000001
  kinematics_solver_timeout: 5.0050000000000000001
  position_only_ik: True

head:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 5.0050000000000000001
  kinematics_solver_timeout: 5.0050000000000000001
  position_only_ik: True

# left_fingers:
#   kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
#   kinematics_solver_search_resolution: 0.0050000000000000001
#   kinematics_solver_timeout: 0.0050000000000000001
#   position_only_ik: True

# right_fingers:
#   kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
#   kinematics_solver_search_resolution: 0.0050000000000000001
#   kinematics_solver_timeout: 0.0050000000000000001
#   position_only_ik: True

  