moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  publish_rate: 100
  controller_names:
    - left_arm_controller
    - right_arm_controller
    - head_controller
    - left_finger_controller
    - right_finger_controller

  left_arm_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - left_arm_joint
      - left_sholder_joint
      - left_biceps_joint
      - left_elbow_joint
      - left_wrist_joint
      - left_hand_joint

  right_arm_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - right_arm_joint
      - right_sholder_joint
      - right_biceps_joint
      - right_elbow_joint
      - right_wrist_joint
      - right_hand_joint

  left_finger_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - left_finger_4_link_1_joint
      - left_finger_3_link_1_joint
      - left_finger_2_link_1_joint
      - left_finger_1_link_1_joint
      - left_finger_4_link_2_joint
      - left_finger_3_link_2_joint
      - left_finger_2_link_2_joint
      - left_finger_1_link_2_joint
      - left_finger_4_link_3_joint
      - left_finger_3_link_3_joint
      - left_finger_2_link_3_joint
      - left_finger_1_link_3_joint
      - left_finger_5_link_1_joint
      - left_finger_5_link_2_joint
      - left_finger_5_link_3_joint


  right_finger_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - right_finger_4_link_1_joint
      - right_finger_3_link_1_joint
      - right_finger_2_link_1_joint
      - right_finger_1_link_1_joint
      - right_finger_4_link_2_joint
      - right_finger_3_link_2_joint
      - right_finger_2_link_2_joint
      - right_finger_1_link_2_joint
      - right_finger_4_link_3_joint
      - right_finger_3_link_3_joint
      - right_finger_2_link_3_joint
      - right_finger_1_link_3_joint
      - right_finger_5_link_1_joint
      - right_finger_5_link_2_joint
      - right_finger_5_link_3_joint


  head_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - neck_joint
      - head_joint









